name: oao_dev
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.10
  - matplotlib>=3.7.0
  - numpy>=1.24.2
  - pandas>=1.5.3 
  - pip
  - pytorch
  - scipy>=1.10.1
  - torchvision
  - pip:
    - ax-platform>=0.3.1
